
// ESTE ARQUIVO FOI DEPRECIADO E NÃO É MAIS UTILIZADO.
// TODOS OS DADOS SÃO AGORA GERENCIADOS VIA SERVICES/STORAGE.TS
// VOCÊ PODE DELETAR ESTE ARQUIVO COM SEGURANÇA.

export const DEPRECATED = true;
